import {demoEvents,match} from './events.js';
import {at,story,clock} from './stories.js';
const xml=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=(value,max)=>String(value??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').trim().slice(0,max);
export function createMemory(index,prefs,{name='',note='',photo=''}={},narrative=null){
 prefs={mode:['fan','analyst','broadcast'].includes(prefs?.mode)?prefs.mode:'fan',language:prefs?.language==='es'?'es':'en',team:['all',match.home,match.away].includes(prefs?.team)?prefs.team:'all',player:['all',...demoEvents.map(e=>e.player)].includes(prefs?.player)?prefs.player:'all'};
 const state=at(index),base=story(state,prefs);
 if(photo&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(photo))throw new Error('Use a PNG, JPEG or WebP photo');
 if(photo.length>1500000)throw new Error('Photo is too large');
 const accepted=narrative&&['computed','foundry-local','azure'].includes(narrative.provider)&&Array.isArray(narrative.evidence)&&narrative.evidence.includes(state.latest.id)&&narrative.evidence.every(id=>state.context.some(e=>e.id===id));
 const source=accepted?narrative:base;
 return {version:1,eventId:state.latest.id,clock:state.clock,synthetic:true,prefs:{...prefs},name:clean(name,32),note:clean(note,140),photo,observed:base.observed,title:base.title,interpretation:clean(source.interpretation,650),provider:source.provider,evidenceOrigin:source.evidenceOrigin||(source.provider==='computed'?'computed':'model-selected'),evidence:[...source.evidence]};
}
export function memoryLink(memory,base){
 const url=new URL(base);url.hash=new URLSearchParams({moment:memory.eventId,lens:memory.prefs.mode,lang:memory.prefs.language,club:memory.prefs.team,player:memory.prefs.player}).toString();return url.href;
}
export function parseMomentLink(hash){
 const params=new URLSearchParams(hash.replace(/^#/,''));const index=demoEvents.findIndex(e=>e.id===params.get('moment'));if(index<0)return null;
 const choose=(key,allowed,fallback)=>allowed.includes(params.get(key))?params.get(key):fallback;
 return {index,prefs:{mode:choose('lens',['fan','analyst','broadcast'],'fan'),language:choose('lang',['en','es'],'en'),team:choose('club',['all',match.home,match.away],'all'),player:choose('player',['all',...demoEvents.map(e=>e.player)],'all')}};
}
const lines=(text,width)=>{const words=String(text).split(/\s+/).flatMap(w=>w.match(new RegExp('.{1,'+width+'}','gu'))||[]),out=[];let line='';for(const w of words){if(line&&line.length+w.length+1>width){out.push(line);line=w;}else line+=(line?' ':'')+w;}if(line)out.push(line);return out;};
export function memorySVG(memory){
 const index=demoEvents.findIndex(e=>e.id===memory.eventId);if(index<0)throw new Error('Unknown memory event');const state=at(index),e=state.latest;
 const point=p=>e.team===match.home?p:[105-p[0],68-p[1]];const from=point(e.from||e.ball),to=e.to?point(e.to):from;
 const note=lines(memory.note||'A moment worth remembering.',47).slice(0,4);
 const observations=lines(memory.observed,65).slice(0,3);
 return `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="1000" viewBox="0 0 800 1000"><defs><linearGradient id="edge" x2="1" y2="1"><stop stop-color="#00cfff"/><stop offset="1" stop-color="#0055dd"/></linearGradient></defs><rect width="800" height="1000" rx="28" fill="#020712"/><rect x="18" y="18" width="764" height="964" rx="20" fill="none" stroke="url(#edge)" stroke-width="3"/><g font-family="Arial,Helvetica,sans-serif"><text x="48" y="76" fill="#f4f8ff" font-size="32" font-weight="bold">PRO-VISION</text><text x="48" y="107" fill="#00cfff" font-size="14" letter-spacing="3">MY MATCH. MY MEMORY.</text><text x="48" y="162" fill="#fff" font-size="${memory.name.length>20?21:29}" font-weight="bold">${xml(memory.name?memory.name+"’s moment":'Your moment')}</text><text x="48" y="201" fill="#ffe200" font-size="18">${xml(clock(state.clock)+' · '+e.player+' · '+e.team)}</text>${memory.photo?`<image href="${memory.photo}" x="48" y="229" width="704" height="172" preserveAspectRatio="xMidYMid slice"/>`:'<rect x="48" y="229" width="704" height="172" rx="10" fill="#071b39"/><text x="76" y="285" fill="#00cfff" font-size="16">THE MOMENT THAT STAYS WITH YOU</text><text x="76" y="347" fill="#fff" font-size="45" font-weight="bold">'+xml(e.type.toUpperCase()+' · '+e.outcome.toUpperCase())+'</text>'}<svg x="48" y="426" width="704" height="320" viewBox="-3 -3 111 74"><rect width="105" height="68" rx="1" fill="#10372f"/><g stroke="#88bcab" stroke-width=".3" fill="none"><rect width="105" height="68"/><path d="M52.5 0V68 M0 14H16.5V54H0 M105 14H88.5V54H105"/><circle cx="52.5" cy="34" r="9.15"/></g><path d="M${from[0]} ${from[1]}L${to[0]} ${to[1]}" stroke="#00cfff" stroke-width="1"/><circle cx="${to[0]}" cy="${to[1]}" r="1.6" fill="#ffe200"/></svg>${note.map((line,i)=>`<text x="48" y="${772+i*24}" fill="#f4f8ff" font-size="20">${xml(line)}</text>`).join('')}${observations.map((line,i)=>`<text x="48" y="${889+i*17}" fill="#a5b8d0" font-size="13">${xml(line)}</text>`).join('')}<text x="48" y="950" fill="#00cfff" font-size="12">SYNTHETIC MATCH EXCERPT · ${xml(memory.evidence.join(' / '))}</text></g></svg>`;
}
export function memoryHTML(memory){
 const index=demoEvents.findIndex(e=>e.id===memory.eventId);if(index<0)throw new Error('Unknown memory event');const state=at(index);
 const fan=story(state,{...memory.prefs,mode:'fan'}),analyst=story(state,{...memory.prefs,mode:'analyst'});
 return `<!doctype html><html lang="${memory.prefs.language==='es'?'es':'en'}"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PRO-VISION · My match memory</title><style>body{margin:0;background:#020712;color:#f4f8ff;font:16px Arial,sans-serif}main{max-width:740px;margin:auto;padding:24px}svg{display:block;width:100%;height:auto}h1{color:#00cfff}section,details{padding:18px;border:1px solid #007bff;border-radius:8px;margin:16px 0}summary{cursor:pointer;color:#00cfff}p{line-height:1.6}.analyst{display:none}#analyst:checked~.analyst{display:block}#analyst:checked~.fan{display:none}label{margin-right:18px;color:#00cfff}small{color:#a5b8d0}</style><main><h1>My match. My memory.</h1>${memorySVG(memory)}<section><h2>The recorded moment</h2><p>${xml(memory.observed)}</p><input id="fan" type="radio" name="lens" checked><label for="fan">Fan lens</label><input id="analyst" type="radio" name="lens"><label for="analyst">Analyst lens</label><p class="fan">${xml(fan.interpretation)}</p><p class="analyst">${xml(analyst.interpretation)}</p><small>These two lenses use computed templates.</small></section><section><h2>Saved interpretation</h2><p>${xml(memory.interpretation)}</p><small>${xml(memory.provider==='computed'?'Computed explanation':'AI interpretation, not independently verified')} · Synthetic football excerpt${memory.evidenceOrigin==='computed-input'?' · Source IDs assigned from computed input context':''}</small></section><details><summary>Explore the evidence</summary>${memory.evidence.map(id=>{const e=state.context.find(x=>x.id===id);return e?`<details><summary>${xml(id+' · '+clock(e.second)+' · '+e.player)}</summary><p>${xml(e.team+' · '+e.type+' · '+e.outcome)}</p></details>`:'';}).join('')}</details><p><small>Your note and photo are personal additions, not match evidence. This downloaded file works offline. No XtremeSignPost API, clothing tag or patent ownership is asserted.</small></p></main></html>`;
}
